server:
  port: ${PORT:2333}
  address: 0.0.0.0

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:changeme}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    # 下面这些保持默认就行
    bufferDurationMs: 400
    frameBufferDurationMs: 1000
    trackStuckThresholdMs: 10000
    useSeekGhosting: true

logging:
  level:
    root: INFO
    lavalink: INFO


